// Code generated by "stringer -type=Weekday"; DO NOT EDIT.

package types

import (
	"strconv"
)

//go:generate stringer -type=Weekday
type Weekday int

const (
	Sunday Weekday = iota
	Monday
	Tuesday
	Wednesday
	Thursday
	Friday
	Saturday
)

// Weekday names for Swagger documentation
// swagger:enum Weekday
const (
	_Sunday    = "Sunday"
	_Monday    = "Monday"
	_Tuesday   = "Tuesday"
	_Wednesday = "Wednesday"
	_Thursday  = "Thursday"
	_Friday    = "Friday"
	_Saturday  = "Saturday"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sunday-0]
	_ = x[Monday-1]
	_ = x[Tuesday-2]
	_ = x[Wednesday-3]
	_ = x[Thursday-4]
	_ = x[Friday-5]
	_ = x[Saturday-6]
}

const _Weekday_name = "SundayMondayTuesdayWednesdayThursdayFridaySaturday"

var _Weekday_index = [...]uint8{0, 6, 12, 19, 28, 36, 42, 50}

func (i Weekday) String() string {
	if i < 0 || i >= Weekday(len(_Weekday_index)-1) {
		return "Weekday(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Weekday_name[_Weekday_index[i]:_Weekday_index[i+1]]
}
