version: '2.1'
services:
  server:
    image: comvoca
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /tmp/app:/var/log/app
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=local
      - APP_DSN=postgres://db/go_restful?sslmode=disable&user=postgres&password=postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres:alpine"
    container_name: "postgres_db"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "comvoca"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
