server:
  port: 3000
  memory_profile: true
  cpu_profile: true
  region: ca-central-1
database:
  host:  ${DB_HOST:pss-db.ci20zoupdt0d.ca-central-1.rds.amazonaws.com}
  port: ${DB_PORT:5432}
  username: ${DB_USERNAME:comvoca_dev_user}
  password: ${DB_PASSWORD:v+6H4af7t?Mv}
  dbname: ${DB_NAME:comvoca_dev}
auth:
  cognito:
    user_pool_id: ca-central-1_Tn7axDK23
    client_id: 10dmu7nqovmr5n906mrhj4h056
    secret: 4r4conqo7pq68455o5ts6lv4qren409mv6mkfmngkg7ijsvg16b
    redirect_url: https://comvoca.com
    issuer_url: https://cognito-idp.ca-central-1.amazonaws.com/ca-central-1_3x2wMFDS0
    jwt_secret: uwYuAzCmY2WopusFLGZJxua49hdHgs4d_Q86KWe_XwspTlQFclmXXi444cSDDga3u1zcHDZS0XAl8Xh_ZnP4vDQwH3smBYovJykLBn59HM49tqmLolfGtjwqLJbmtsu6cPGJPhTBwr3Kq2BldcBmwtMjD9lsQ8nBdIzMVlcwaIay2Yq1-cAcCGX-KReKWugyqIr4qk3HvrI0U0eIMbAxC83CW01TbNPiP-s13dxCZSboTejucm-35hXdM7o09xq_WCpt-HNn_MyAtF9jxWx3SWBpEOMC1zcbk4Bg8-z2vr64dtTf85zxn0q-d8Bqx8s0XNtM2p1zL2dG6qeCy9KGUQ
    token_expire_hour: 24
    region: ca-central-1
application:
  debug: true
  profile: dev
  base_url: http://comvoc-publi-1wzhn1cj79pp-1604823533.ca-central-1.elb.amazonaws.com
  body_limit_size: 52428800 #50MB

